language: java
sudo: false
jdk:
- oraclejdk8
dist: trusty
addons:
  chrome: stable
  firefox: latest
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_2f990b57978e_key -iv $encrypted_2f990b57978e_iv
  -in gradle.properties.enc -out gradle.properties -d || true
install:
- wget 'https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.zip'
- wget 'https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip'
- sudo apt-get install -y unzip
- mkdir -p $TRAVIS_BUILD_DIR/drivers
- unzip chromedriver_linux64.zip -d $TRAVIS_BUILD_DIR/drivers
- tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C $TRAVIS_BUILD_DIR/drivers
- PATH=$PATH:$TRAVIS_BUILD_DIR/drivers
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: ./gradle/buildViaTravis.sh
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- ./gradlew jacocoTestReport coveralls
